### ISSUE TITLE
Decide on preferred linter and document

### ISSUE THREAD

**Issue by kelle** [astrodbtoolkit/astrodb_utils#71]
I think both David and I have been using `ruff`.  We could document that as our preference and add it as a pre-commit hook.

**Comment by kelle** [comment]
I think we should use BOTH Black and Ruff.  Black for formatting and Ruff for "fixes".  Something like this: 
https://github.com/astral-sh/ruff-vscode/issues/126

I think I want Black to autoformat but maybe I just want Ruff to tell me things and NOT autoformat.

**Comment by kelle** [comment]
Maybe we want to go ahead and add the Black auto hook thing. I think it's better to do sooner rather than later.

**Comment by dr-rodriguez** [comment]
I would recommend instead of a Black pre-commit hook to instead use darker. Darker applies the same styling as Black but only on lines changed in a commit. So instead of changing the full file it only changes a few lines.

Example .pre-commit-config.yaml file:
```
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# To install:
# pip install pre-commit
# pre-commit install --allow-missing-config
repos:
- repo: https://github.com/akaihola/darker
  rev: 1.7.2
  hooks:
    - id: darker
```
